const propiedades = [
    {
        id: 1,
        nombre: "Casa en Providencia",
        direccion: {
            calle: "Avenida Providencia",
            numero: 1234,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Providencia",
            codigoPostal: "7500000",
        },
        precio: 350000000,
        superficie: 180,
        habitaciones: 5,
        baños: 3,
        tipoPropiedad: "Casa",
        descripcion: "Casa espaciosa cerca del centro comercial.",
        imagenUrl: "https://socovesa.vercel.app/images/aerial-view-of-tightly-located-new-family-houses-i-2023-11-27-05-19-01-utc.jpg",
        amenities: ["Jardín", "Piscina", "Gimnasio", "Estacionamiento"],
        agente: {
            nombre: "Ana Gómez",
            telefono: "+56 9 2345 6789",
            email: "ana.gomez@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 2,
        nombre: "Departamento en Las Condes",
        direccion: {
            calle: "Avenida Apoquindo",
            numero: 4321,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Las Condes",
            codigoPostal: "7550000",
        },
        precio: 150000000,
        superficie: 80,
        habitaciones: 3,
        baños: 2,
        tipoPropiedad: "Departamento",
        descripcion: "Moderno departamento con excelente vista.",
        imagenUrl: "https://socovesa.vercel.app/images/rows-of-new-townhomes-2023-11-27-05-01-23-utc.jpg",
        amenities: ["Piscina", "Estacionamiento", "Seguridad 24h"],
        agente: {
            nombre: "Carlos Soto",
            telefono: "+56 9 8765 4321",
            email: "carlos.soto@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 3,
        nombre: "Casa en Ñuñoa",
        direccion: {
            calle: "Irarrázaval",
            numero: 987,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Ñuñoa",
            codigoPostal: "7750000",
        },
        precio: 280000000,
        superficie: 140,
        habitaciones: 4,
        baños: 3,
        tipoPropiedad: "Casa",
        descripcion: "Casa acogedora en barrio tranquilo, cercana a parques.",
        imagenUrl: "https://socovesa.vercel.app/images/august-17-2017-pervalka-village-lithuania-old-l-2023-11-27-05-04-27-utc.jpg",
        amenities: ["Jardín", "Terraza", "Cerca de transporte público"],
        agente: {
            nombre: "María López",
            telefono: "+56 9 7654 3210",
            email: "maria.lopez@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 4,
        nombre: "Departamento en Vitacura",
        direccion: {
            calle: "Avenida Vitacura",
            numero: 5432,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Vitacura",
            codigoPostal: "7630000",
        },
        precio: 320000000,
        superficie: 120,
        habitaciones: 4,
        baños: 3,
        tipoPropiedad: "Departamento",
        descripcion: "Departamento de lujo en una de las mejores zonas de Santiago.",
        imagenUrl: "https://socovesa.vercel.app/images/beautiful-shot-of-old-brick-houses-in-a-row-on-a-s-2023-11-27-05-18-05-utc.jpeg",
        amenities: ["Piscina", "Estacionamiento", "Seguridad 24h"],
        agente: {
            nombre: "Felipe Torres",
            telefono: "+56 9 6543 2109",
            email: "felipe.torres@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 5,
        nombre: "Casa en La Reina",
        direccion: {
            calle: "Avenida Larraín",
            numero: 6789,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "La Reina",
            codigoPostal: "7850000",
        },
        precio: 290000000,
        superficie: 160,
        habitaciones: 4,
        baños: 2,
        tipoPropiedad: "Casa",
        descripcion: "Amplia casa familiar con gran jardín.",
        imagenUrl: "https://socovesa.vercel.app/images/casa-de-pedra-museum-19th-century-stone-house-2023-11-27-05-25-58-utc.jpg",
        amenities: ["Jardín", "Estacionamiento", "Cerca de colegios"],
        agente: {
            nombre: "José Martínez",
            telefono: "+56 9 5432 1098",
            email: "jose.martinez@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 6,
        nombre: "Departamento en Santiago Centro",
        direccion: {
            calle: "Alameda",
            numero: 123,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Santiago Centro",
            codigoPostal: "8320000",
        },
        precio: 180000000,
        superficie: 70,
        habitaciones: 2,
        baños: 1,
        tipoPropiedad: "Departamento",
        descripcion: "Departamento céntrico, ideal para ejecutivos.",
        imagenUrl: "https://socovesa.vercel.app/images/detail-of-colorful-houses-2023-11-27-04-59-08-utc.jpg",
        amenities: ["Cerca de transporte público", "Seguridad 24h", "Estacionamiento"],
        agente: {
            nombre: "Lorena Álvarez",
            telefono: "+56 9 4321 0987",
            email: "lorena.alvarez@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 7,
        nombre: "Casa en Peñalolén",
        direccion: {
            calle: "Avenida Grecia",
            numero: 2345,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Peñalolén",
            codigoPostal: "7910000",
        },
        precio: 250000000,
        superficie: 150,
        habitaciones: 4,
        baños: 2,
        tipoPropiedad: "Casa",
        descripcion: "Casa cómoda en barrio residencial.",
        imagenUrl: "https://socovesa.vercel.app/images/facade-of-cottage-and-retro-carriage-2023-11-27-05-05-02-utc.jpg",
        amenities: ["Jardín", "Cerca de colegios", "Estacionamiento"],
        agente: {
            nombre: "Pedro Castillo",
            telefono: "+56 9 3210 9876",
            email: "pedro.castillo@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 8,
        nombre: "Departamento en La Florida",
        direccion: {
            calle: "Avenida Vicuña Mackenna",
            numero: 8765,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "La Florida",
            codigoPostal: "8240000",
        },
        precio: 170000000,
        superficie: 65,
        habitaciones: 2,
        baños: 1,
        tipoPropiedad: "Departamento",
        descripcion: "Departamento moderno con excelente conectividad.",
        imagenUrl: "https://socovesa.vercel.app/images/rooflines-in-the-neighborhood-at-sunset-in-the-spr-2023-11-27-05-07-36-utc.jpg",
        amenities: ["Cerca de transporte público", "Seguridad 24h", "Estacionamiento"],
        agente: {
            nombre: "Cecilia Moya",
            telefono: "+56 9 2109 8765",
            email: "cecilia.moya@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 9,
        nombre: "Casa en Macul",
        direccion: {
            calle: "Avenida Macul",
            numero: 3456,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Macul",
            codigoPostal: "7810000",
        },
        precio: 260000000,
        superficie: 140,
        habitaciones: 4,
        baños: 2,
        tipoPropiedad: "Casa",
        descripcion: "Casa bien ubicada, ideal para familias.",
        imagenUrl: "https://socovesa.vercel.app/images/row-of-houses-in-bristol-england-2023-11-27-04-58-17-utc.jpg",
        amenities: ["Jardín", "Estacionamiento", "Cerca de colegios"],
        agente: {
            nombre: "Roberto Díaz",
            telefono: "+56 9 1098 7654",
            email: "roberto.diaz@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 10,
        nombre: "Departamento en San Miguel",
        direccion: {
            calle: "Avenida Departamental",
            numero: 6543,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "San Miguel",
            codigoPostal: "8900000",
        },
        precio: 160000000,
        superficie: 60,
        habitaciones: 2,
        baños: 1,
        tipoPropiedad: "Departamento",
        descripcion: "Departamento en excelente ubicación, con vista despejada.",
        imagenUrl: "https://socovesa.vercel.app/images/rows-of-new-townhomes-2023-11-27-05-01-23-utc.jpg",
        amenities: ["Cerca de transporte público", "Seguridad 24h", "Estacionamiento"],
        agente: {
            nombre: "Patricia Morales",
            telefono: "+56 9 0987 6543",
            email: "patricia.morales@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 11,
        nombre: "Casa en Maipú",
        direccion: {
            calle: "Avenida Pajaritos",
            numero: 8765,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Maipú",
            codigoPostal: "9250000",
        },
        precio: 220000000,
        superficie: 130,
        habitaciones: 3,
        baños: 2,
        tipoPropiedad: "Casa",
        descripcion: "Casa moderna en barrio tranquilo.",
        imagenUrl: "https://socovesa.vercel.app/images/street-with-modern-family-houses-2023-11-27-05-00-49-utc.jpg",
        amenities: ["Jardín", "Cerca de colegios", "Estacionamiento"],
        agente: {
            nombre: "Andrés Núñez",
            telefono: "+56 9 9876 5432",
            email: "andres.nunez@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 12,
        nombre: "Departamento en Recoleta",
        direccion: {
            calle: "Avenida Recoleta",
            numero: 5432,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Recoleta",
            codigoPostal: "8420000",
        },
        precio: 140000000,
        superficie: 55,
        habitaciones: 2,
        baños: 1,
        tipoPropiedad: "Departamento",
        descripcion: "Departamento accesible con excelente conectividad.",
        imagenUrl: "https://socovesa.vercel.app/images/timber-colorful-house-in-the-countryside-of-chile-2023-11-27-05-04-52-utc.jpg",
        amenities: ["Cerca de transporte público", "Seguridad 24h", "Estacionamiento"],
        agente: {
            nombre: "Verónica Araya",
            telefono: "+56 9 8765 4321",
            email: "veronica.araya@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 13,
        nombre: "Casa en Puente Alto",
        direccion: {
            calle: "Avenida Concha y Toro",
            numero: 2345,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Puente Alto",
            codigoPostal: "8150000",
        },
        precio: 190000000,
        superficie: 120,
        habitaciones: 3,
        baños: 2,
        tipoPropiedad: "Casa",
        descripcion: "Casa amplia con patio grande, ideal para familias.",
        imagenUrl: "https://socovesa.vercel.app/images/timber-colorful-house-in-the-countryside-of-chile-2023-11-27-05-36-51-utc.jpg",
        amenities: ["Jardín", "Estacionamiento", "Cerca de colegios"],
        agente: {
            nombre: "Alejandro Fuentes",
            telefono: "+56 9 7654 3210",
            email: "alejandro.fuentes@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 14,
        nombre: "Departamento en Independencia",
        direccion: {
            calle: "Avenida Independencia",
            numero: 8765,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Independencia",
            codigoPostal: "8380000",
        },
        precio: 150000000,
        superficie: 60,
        habitaciones: 2,
        baños: 1,
        tipoPropiedad: "Departamento",
        descripcion: "Departamento luminoso con excelente ubicación.",
        imagenUrl: "https://socovesa.vercel.app/images/view-from-above-of-densely-built-residential-house-2023-11-27-05-08-12-utc.jpg",
        amenities: ["Cerca de transporte público", "Seguridad 24h", "Estacionamiento"],
        agente: {
            nombre: "Beatriz Rojas",
            telefono: "+56 9 6543 2109",
            email: "beatriz.rojas@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 15,
        nombre: "Casa en Quilicura",
        direccion: {
            calle: "Avenida Lo Marcoleta",
            numero: 3456,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Quilicura",
            codigoPostal: "8700000",
        },
        precio: 210000000,
        superficie: 140,
        habitaciones: 4,
        baños: 2,
        tipoPropiedad: "Casa",
        descripcion: "Casa moderna en barrio residencial.",
        imagenUrl: "https://socovesa.vercel.app/images/aerial-view-of-tightly-located-new-family-houses-i-2023-11-27-05-19-01-utc.jpg",
        amenities: ["Jardín", "Cerca de colegios", "Estacionamiento"],
        agente: {
            nombre: "Luis Sánchez",
            telefono: "+56 9 5432 1098",
            email: "luis.sanchez@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 16,
        nombre: "Departamento en La Cisterna",
        direccion: {
            calle: "Avenida Américo Vespucio",
            numero: 6543,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "La Cisterna",
            codigoPostal: "7970000",
        },
        precio: 130000000,
        superficie: 55,
        habitaciones: 2,
        baños: 1,
        tipoPropiedad: "Departamento",
        descripcion: "Departamento cómodo y accesible.",
        imagenUrl: "https://socovesa.vercel.app/images/aerial-view-of-tightly-located-new-family-houses-i-2024-01-30-01-07-55-utc.jpg",
        amenities: ["Cerca de transporte público", "Seguridad 24h", "Estacionamiento"],
        agente: {
            nombre: "Elena Vargas",
            telefono: "+56 9 4321 0987",
            email: "elena.vargas@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 17,
        nombre: "Casa en San Bernardo",
        direccion: {
            calle: "Avenida Portales",
            numero: 9876,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "San Bernardo",
            codigoPostal: "8050000",
        },
        precio: 240000000,
        superficie: 160,
        habitaciones: 4,
        baños: 3,
        tipoPropiedad: "Casa",
        descripcion: "Casa familiar con gran jardín.",
        imagenUrl: "https://socovesa.vercel.app/images/august-17-2017-pervalka-village-lithuania-old-l-2023-11-27-05-04-27-utc.jpg",
        amenities: ["Jardín", "Cerca de colegios", "Estacionamiento"],
        agente: {
            nombre: "Fernando Paredes",
            telefono: "+56 9 3210 9876",
            email: "fernando.paredes@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 18,
        nombre: "Departamento en Lo Barnechea",
        direccion: {
            calle: "Avenida El Rodeo",
            numero: 4321,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Lo Barnechea",
            codigoPostal: "7690000",
        },
        precio: 350000000,
        superficie: 150,
        habitaciones: 3,
        baños: 3,
        tipoPropiedad: "Departamento",
        descripcion: "Departamento de lujo con vista a la cordillera.",
        imagenUrl: "https://socovesa.vercel.app/images/beautiful-shot-of-old-brick-houses-in-a-row-on-a-s-2023-11-27-05-18-05-utc.jpeg",
        amenities: ["Piscina", "Seguridad 24h", "Estacionamiento"],
        agente: {
            nombre: "Cristina Figueroa",
            telefono: "+56 9 2109 8765",
            email: "cristina.figueroa@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 19,
        nombre: "Casa en La Granja",
        direccion: {
            calle: "Avenida Santa Rosa",
            numero: 6543,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "La Granja",
            codigoPostal: "8780000",
        },
        precio: 170000000,
        superficie: 110,
        habitaciones: 3,
        baños: 2,
        tipoPropiedad: "Casa",
        descripcion: "Casa acogedora con excelente conectividad.",
        imagenUrl: "https://socovesa.vercel.app/images/casa-de-pedra-museum-19th-century-stone-house-2023-11-27-05-25-58-utc.jpg",
        amenities: ["Jardín", "Cerca de colegios", "Estacionamiento"],
        agente: {
            nombre: "Sebastián Reyes",
            telefono: "+56 9 1098 7654",
            email: "sebastian.reyes@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 20,
        nombre: "Departamento en El Bosque",
        direccion: {
            calle: "Avenida Lo Blanco",
            numero: 5432,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "El Bosque",
            codigoPostal: "8010000",
        },
        precio: 120000000,
        superficie: 50,
        habitaciones: 2,
        baños: 1,
        tipoPropiedad: "Departamento",
        descripcion: "Departamento económico en zona residencial.",
        imagenUrl: "https://socovesa.vercel.app/images/detail-of-colorful-houses-2023-11-27-04-59-08-utc.jpg",
        amenities: ["Cerca de transporte público", "Seguridad 24h", "Estacionamiento"],
        agente: {
            nombre: "Silvana Miranda",
            telefono: "+56 9 0987 6543",
            email: "silvana.miranda@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 21,
        nombre: "Casa en Huechuraba",
        direccion: {
            calle: "Avenida Recoleta",
            numero: 3456,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Huechuraba",
            codigoPostal: "8580000",
        },
        precio: 270000000,
        superficie: 140,
        habitaciones: 4,
        baños: 2,
        tipoPropiedad: "Casa",
        descripcion: "Casa moderna en barrio tranquilo.",
        imagenUrl: "https://socovesa.vercel.app/images/rooflines-in-the-neighborhood-at-sunset-in-the-spr-2023-11-27-05-07-36-utc.jpg",
        amenities: ["Jardín", "Estacionamiento", "Cerca de colegios"],
        agente: {
            nombre: "Tomás Valenzuela",
            telefono: "+56 9 8765 4321",
            email: "tomas.valenzuela@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 22,
        nombre: "Departamento en Cerrillos",
        direccion: {
            calle: "Avenida Cerrillos",
            numero: 6543,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Cerrillos",
            codigoPostal: "9200000",
        },
        precio: 140000000,
        superficie: 60,
        habitaciones: 2,
        baños: 1,
        tipoPropiedad: "Departamento",
        descripcion: "Departamento con buena conectividad.",
        imagenUrl: "https://socovesa.vercel.app/images/street-with-modern-family-houses-2023-11-27-05-00-49-utc.jpg",
        amenities: ["Cerca de transporte público", "Seguridad 24h", "Estacionamiento"],
        agente: {
            nombre: "Gabriela Muñoz",
            telefono: "+56 9 7654 3210",
            email: "gabriela.munoz@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 23,
        nombre: "Casa en Renca",
        direccion: {
            calle: "Avenida Renca",
            numero: 5432,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Renca",
            codigoPostal: "8640000",
        },
        precio: 200000000,
        superficie: 130,
        habitaciones: 3,
        baños: 2,
        tipoPropiedad: "Casa",
        descripcion: "Casa en excelente ubicación, con amplio jardín.",
        imagenUrl: "https://socovesa.vercel.app/images/timber-colorful-house-in-the-countryside-of-chile-2023-11-27-05-04-52-utc.jpg",
        amenities: ["Jardín", "Estacionamiento", "Cerca de colegios"],
        agente: {
            nombre: "Claudia Fernández",
            telefono: "+56 9 6543 2109",
            email: "claudia.fernandez@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 24,
        nombre: "Departamento en San Joaquín",
        direccion: {
            calle: "Avenida Carlos Valdovinos",
            numero: 4321,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "San Joaquín",
            codigoPostal: "8940000",
        },
        precio: 160000000,
        superficie: 65,
        habitaciones: 2,
        baños: 1,
        tipoPropiedad: "Departamento",
        descripcion: "Departamento con excelente conectividad y vista despejada.",
        imagenUrl: "https://socovesa.vercel.app/images/timber-colorful-house-in-the-countryside-of-chile-2023-11-27-05-36-51-utc.jpg",
        amenities: ["Cerca de transporte público", "Seguridad 24h", "Estacionamiento"],
        agente: {
            nombre: "Marta Salazar",
            telefono: "+56 9 5432 1098",
            email: "marta.salazar@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    },
    {
        id: 25,
        nombre: "Casa en Lo Espejo",
        direccion: {
            calle: "Avenida Lo Espejo",
            numero: 8765,
            ciudad: "Santiago",
            region: "Metropolitana",
            comuna: "Lo Espejo",
            codigoPostal: "9120000",
        },
        precio: 180000000,
        superficie: 120,
        habitaciones: 3,
        baños: 2,
        tipoPropiedad: "Casa",
        descripcion: "Casa cómoda en barrio residencial.",
        imagenUrl: "https://socovesa.vercel.app/images/view-from-above-of-densely-built-residential-house-2023-11-27-05-08-12-utc.jpg",
        amenities: ["Jardín", "Estacionamiento", "Cerca de colegios"],
        agente: {
            nombre: "Alberto Gutiérrez",
            telefono: "+56 9 4321 0987",
            email: "alberto.gutierrez@socovesa.com",
        },
        fechaPublicacion: "2024-08-20",
    }
];

export default function handler(req, res) {
    res.status(200).json(propiedades);
}
